
create table players (
  id int generated by default as identity primary key,
  firstname character varying (32) not null,
  lastname character varying (32) not null,
  age int,
  race character varying (32) not null,
  text character varying (256) not null
);

insert into players (firstname, lastname, age, race, text) values ('ali', 'Valievich', 20, "Asian", 'lorem ipsum dolor set amet ....');